services:
  - type: web
    name: al-aqiq-store
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: ADMIN_PASSWORD
        value: admin123